version: '3.6'
services:
  zoo1:
    hostname: zoo1
    image: zookeeper
    ports:
    - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
    - net

  zoo2:
    hostname: zoo2
    image: zookeeper
    ports:
    - 2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
    - net

  zoo3:
    hostname: zoo3
    image: zookeeper
    ports:
    - 2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
    - net

  kafka:
    hostname: kafka
    image: kafka
    ports:
    - 9092
    deploy:
      replicas: 1
    environment:
      ZK_HOSTS: "zoo1:2181,zoo2:2181,zoo3:2181"
      TOPIC_LIST: "topic1:1:2,topic2:1:3"
      AUTO_GEN_BROKER_ID: "true"
      ZK_CHROOT: "test"
    networks:
    - net

networks:
  net: